theme: jekyll-theme-cayman
exclude: ["*.gz", "Date-Holidays-*","cpanfile", "cpanfile.snapshot", "prototypes", "scripts", "t", "MANIFEST.SKIP", "lib", "Gemfile", "Gemfile.lock", "dist.ini", "dictionary.dic", "local"]
